language: python
python:
    - "2.7"
env:
    - DOCKER_COMPOSE_VERSION=1.21.0
sudo: required
services:
    - docker
dist: trusty
before_install:
    - switch_to_oraclejdk7
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - docker-compose version
    - sudo docker-compose up --build --abort-on-container-exit
    - sudo apt-get update -qq
    - sudo apt-get install -y xvfb
    - sudo apt-get install -y firefox
install: "pip install -r requirements.txt"
before_script:
    - pip install -r test-requirements.txt
    - sudo ln -s . /librarian
script: "sudo docker-compose run test ./dockertests"
after_success: "sudo docker-compose run test pwd && COVERALLS_REPO_TOKEN=$coveralls_token coveralls"
after_failure: "sudo docker-compose run test pwd && COVERALLS_REPO_TOKEN=$coveralls_token coveralls"
