language: python
python:
    - "2.7"
sudo: required
services:
    - docker
dist: trusty
before_install:
    - switch_to_oraclejdk7
    - docker-compose version
    - sudo docker-compose up --build -d
    - sudo apt-get update -qq
    - sudo apt-get install -y xvfb
    - sudo apt-get install -y firefox
install: "pip install -r requirements.txt"
before_script:
    - pip install -r test-requirements.txt
    - sudo ln -s . /librarian
script: "sudo docker-compose run test ls && ./runtests --with-xcoverage && ./run_js_tests"
after_success: "sudo docker-compose run test pwd && COVERALLS_REPO_TOKEN=$coveralls_token coveralls"
after_failure: "sudo docker-compose run test pwd && COVERALLS_REPO_TOKEN=$coveralls_token coveralls"
