language: python
python:
    - "2.7"
before_script: "pip install -r test-requirements.txt"
install: "pip install -r requirements.txt"
script: "nosetests --with-xcoverage"
before_install:
    - apt-get install xvfb
    - apt-get install firefox
