language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y xvfb
    - sudo apt-get install -y firefox
    - sudo apt-get install -y mysql-server
    - sudo /etc/init.d/mysql start
    - sudo apt-get install -y mysql-client
install: "pip install -r requirements.txt"
before_script:
    - pip install -r test-requirements.txt
    - fab -H localhost create_database:is_test=True
script: "./runtests --with-xcoverage && ./run_js_tests"
after_success: "COVERALLS_REPO_TOKEN=$coveralls_token coveralls"
after_failure: "COVERALS_REPO_TOKEN=$coveralls_token coveralls"
