version: '2.1'
services:
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=alexandria
    ports:
      - "3309:3306"
  test:
    build:
      context: ./
      dockerfile: Dockerfile-test
    volumes:
      - .:/librarian
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: "redis:4.0.11"
