# vim: set ft=dockerfile:
FROM alexandria:current

COPY ./test-requirements.txt .
RUN pip install -r test-requirements.txt
RUN apt-get update && apt-get install -y netcat
# This is already mounted in the base image but we are doing it again here to
# prevent the costly first RUN directive above. This way, changes in the code
# does not necessitate rebuilding Dockerfile.
COPY . ./librarian
ENV ALEXANDRIA_CONFIG='config.TestAlexandriaConfig'
ENV alexandria_TESTING='true'
ENV is_travis='1'
# This line is specifically for travis-ci builds.
RUN useradd --create-home --shell /bin/bash travis
CMD ["./wait-for-mysql.sh", "db", "./dockertests", "-v"]
ENTRYPOINT ["/usr/bin/env"]
