# vim: set ft=dockerfile:
FROM alexandria:current

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y xvfb firefox oracle-java8-installer git && \
    apt-get clean
COPY ./test-requirements.txt .
RUN pip install -r test-requirements.txt
# This is already mounted in the base image but we are doing it again here to
# prevent the costly first RUN directive above. This way, changes in the code
# does not necessitate rebuilding Dockerfile.
COPY . ./librarian
ENV ALEXANDRIA_CONFIG='config.TestAlexandriaConfig'
ENV alexandria_TESTING='true'
ENV is_travis='1'
# This line is specifically for travis-ci builds.
RUN useradd --create-home --shell /bin/bash travis
